Tesnsor is the data transfered from layers to layers. 0-dim scalar, 1-dim vector, 2-dim matrix, 3-dim tensor    ## 0,1-dim using lowercase naming, more-dim using uppercaes naming

In [1]:
import torch
import torch.nn.functional as F

In [2]:
scalar = torch.tensor(1)
print(scalar)
print(scalar.ndim)
scalar.shape


tensor(1)
0


torch.Size([])

In [3]:
vector = torch.tensor([1,1])
print(vector)
print(vector.ndim)
vector.shape

tensor([1, 1])
1


torch.Size([2])

In [4]:
MATRIX = torch.tensor([[1,1],
                       [2,2]])
print(MATRIX)
print(MATRIX.ndim)
MATRIX.shape

tensor([[1, 1],
        [2, 2]])
2


torch.Size([2, 2])

In [5]:
TENSOR = torch.tensor([[[1,1,1],
                        [1,2,1],
                        [1,3,1]],
                       
                       [[2,1,2],
                       [2,2,2],
                       [2,3,2]]])
print(TENSOR)
print(TENSOR.ndim)
TENSOR.shape

tensor([[[1, 1, 1],
         [1, 2, 1],
         [1, 3, 1]],

        [[2, 1, 2],
         [2, 2, 2],
         [2, 3, 2]]])
3


torch.Size([2, 3, 3])

Random Tensors

In [6]:
random_tensor = torch.rand(3,4,5)
print(random_tensor)

tensor([[[0.8166, 0.1059, 0.2400, 0.6739, 0.9945],
         [0.5959, 0.2269, 0.3404, 0.3537, 0.8166],
         [0.5254, 0.1756, 0.1242, 0.6511, 0.2069],
         [0.6094, 0.0128, 0.7042, 0.8099, 0.4842]],

        [[0.0439, 0.2033, 0.2358, 0.4643, 0.5792],
         [0.6663, 0.9022, 0.0752, 0.4276, 0.9167],
         [0.4178, 0.7759, 0.9697, 0.8074, 0.0931],
         [0.5882, 0.0120, 0.0768, 0.1770, 0.5482]],

        [[0.8440, 0.9434, 0.2934, 0.0139, 0.3785],
         [0.8899, 0.9369, 0.9312, 0.0320, 0.5234],
         [0.8117, 0.4079, 0.7746, 0.6915, 0.3591],
         [0.5868, 0.0672, 0.0168, 0.5583, 0.3314]]])


Create a random image size tensor

In [7]:
random_image_size_tensor = torch.rand(size=(3,224,224))
                                            #color channel, height, width
print(random_image_size_tensor.ndim)
random_image_size_tensor.shape

3


torch.Size([3, 224, 224])

In [8]:
zeros = torch.zeros(3,4)
print(zeros)
ones = torch.ones(3,4)
print(ones)
ones.dtype


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


torch.float32

creating a range of tensors

In [9]:
one_to_ten = torch.arange(start=1,end=11,step=1)
print(one_to_ten)
zeros_one_to_ten = torch.zeros_like(one_to_ten)
print(zeros_one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [10]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Manipulating Tensors (tensor operatinos)

Addition
Substraction
Multiplication (element-wise)
Division
Matrix multiplication

In [11]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [12]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])


The difference between element-wise multiplication and matrix multiplication

In [13]:
tensor = torch.tensor([1,2,3])

print("temsor*temnsor = {}".format(tensor*tensor))

print("torch.matmul(tensor,tenmsor)={}".format(torch.matmul(tensor,tensor)))

temsor*temnsor = tensor([1, 4, 9])
torch.matmul(tensor,tenmsor)=14


Tensor aggregation (max min mean sum etc.)

In [14]:
x = torch.tensor([0,10,100])

print(torch.max(x),x.max())
print(torch.min(x),x.min())
print(torch.mean(x.type(torch.float32)),x.type(torch.float32).mean())
print(torch.sum(x),x.sum())

tensor(100) tensor(100)
tensor(0) tensor(0)
tensor(36.6667) tensor(36.6667)
tensor(110) tensor(110)


Find positions

In [15]:
x = torch.tensor([1,2,3,4,1,5,6,7,8,9])

print(x.argmax())
print(x.argmin())

tensor(9)
tensor(0)


Reshape View Stack Squeeze Unsqueeze Permute

In [16]:
x = torch.tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
print(x)
x.shape

x_reshaped = x.reshape(4,3)
print(x_reshaped)
x_reshaped.shape

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


torch.Size([4, 3])

In [17]:
x_view = x.view(2,6)
print(x_view)
x_view[0,0]=0 # Like a pointer
print(x_view)
print(x)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
tensor([[ 0,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
tensor([[ 0,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [18]:
x = torch.arange(1,6)
print(x)
x_stacked_0 = torch.stack([x,x,x,x],dim=0)
x_stacked_1 = torch.stack([x,x,x,x],dim=1)
print(x_stacked_0)
print(x_stacked_1)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5]])


In [19]:
x_origin = torch.zeros(2,1,2)
print(x_origin)
print(x_origin.shape)
x_squeezed = x_origin.squeeze()
print(x_squeezed.shape)
print(x_squeezed)

x_unsqueezed_0 = x_squeezed.unsqueeze(0)
print(x_unsqueezed_0)
print(x_unsqueezed_0.shape)

x_unsqueezed_2 = x_squeezed.unsqueeze(2)
print(x_unsqueezed_2)
print(x_unsqueezed_2.shape)

tensor([[[0., 0.]],

        [[0., 0.]]])
torch.Size([2, 1, 2])
torch.Size([2, 2])
tensor([[0., 0.],
        [0., 0.]])
tensor([[[0., 0.],
         [0., 0.]]])
torch.Size([1, 2, 2])
tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])
torch.Size([2, 2, 1])


In [20]:
x_origin = torch.rand(size=(3,224,224))
x_origin.shape
x_permuted = x_origin.permute(1,2,0)
x_permuted.shape

torch.Size([224, 224, 3])

Numpy and Torch

In [21]:
# NumPy array to tensor
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array, tensor)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [22]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
print(tensor, numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]


Reproducibility . using seed to reduce the randomness

In [23]:
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Choose GPUs to speed up the computation ( if have one )

In [24]:
# For Nvidia CUDA
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)


# For Apple Silicon
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(device)


if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

cuda
cpu


Change the tensor to device

In [25]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor_ongpu = torch.tensor([1,2,3],device=device)
print(tensor_ongpu)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3], device='cuda:0')


Science the tensors on the GPU can't convert to the np array because np only runs on the CPU.
use .cpu() to convert tensor on the cpu

In [26]:
tensor_back_cpu = tensor_on_gpu.cpu()
print(tensor_back_cpu)
print(tensor_back_cpu.numpy())

tensor([1, 2, 3])
[1 2 3]
